#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/promptbetter
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#AI
api.key=${API_KEY}
api.base-url=https://api.groq.com/openai/v1/chat/completions
ai.model=llama-3.1-8b-instant


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:script.sql

#JWT
jwt.secret=${PROMPTBETTER_JWT_SECRET}

#CORS


